name: "Copy files via rsync"
description: "Copy files to remote via rsync"
author: "Alexandru Gojinetchi alexandrugojinetchi@gmail.com"

branding:
  icon: upload-cloud
  color: purple

inputs:
  host:
    description: "SSH host"
    required: true
  password:
    description: "SSH password"
    required: true
  username:
    description: "SSH username"
    required: true
  port:
    description: "SSH port"
    required: false
    default: "22"
  source:
    description: "Remote destination path"
    default: ./dist
    required: false
  destination:
    description: "Remote destination path"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/src/entrypoint.sh
        ${{ github.action_path }}/src/entrypoint.sh
      shell: bash
      env:
        SSH_HOST: ${{ inputs.host }}
        SSH_PORT: ${{ inputs.port }}
        SSH_USER: ${{ inputs.username }}
        SSH_PASSWORD: ${{ inputs.password }}
        REMOTE_PATH: ${{ inputs.destination }}
        LOCAL_PATH: ${{ inputs.source }}