name: "Copy files via rsync"
description: "Copy files to remote via rsync"
author: "Alexandru Gojinetchi alexandrugojinetchi@gmail.com"

branding:
  icon: upload-cloud
  color: purple

inputs:
  host:
    description: "SSH host"
    required: true
  port:
    description: "SSH port"
    required: false
    default: "22"
  username:
    description: "SSH username"
    required: true
  key:
    description: "Private SSH key"
    required: true
  source:
    description: "Remote destination path"
    default: ./dist
    required: false
  destination:
    description: "Remote destination path"
    required: true
  exclude:
    description: "Comma-separated list of paths to exclude"
    required: false
  include:
    description: "Comma-separated list of paths to include"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/src/entrypoint.sh
        ${{ github.action_path }}/src/entrypoint.sh
      shell: bash
      env:
        REMOTE_HOST: ${{ inputs.host }}
        REMOTE_PORT: ${{ inputs.port }}
        REMOTE_USER: ${{ inputs.username }}
        SSH_KEY: ${{ inputs.key }}
        REMOTE_PATH: ${{ inputs.destination }}
        LOCAL_PATH: ${{ inputs.source }}
        EXCLUDES: ${{ inputs.exclude }}
        INCLUDES: ${{ inputs.include }}
